title: Breaking barriers: How text-to-speech and speech-to-text technologies can help you create accessible videos
description: Accessibility guide for beginner video creators
theme: just-the-docs
url: https://AnnaKrukowska/BreakingBarriersAccessibleVideos
aux_links:
  Template Repository: https://github.com/AnnKruQA/BreakingBarriersAccessibleVideos

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

#Favicon
favicon_ico: "/Images/DOQATECh_favicon.png"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright 2024 Anna Krukowska. Distributed under the <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"
  
