title: Breaking barriers: How text-to-speech and speech-to-text technologies can help you create accessible videos
description: Accessibility guide for beginner video creators
theme: just-the-docs

url: https://github.com/AnnKruQA/Breaking-barriers-accessible-videos
